### PR TITLE
Feat/doc: add tutorial

### PR DESCRIPTION
**Pull request by Hao-Chalmers**
### Main improvements in this PR:

- doc: update the 'RAVEN mini tutorial.docx' file by providing an additional exercise on the use of entire workflow on _de novo_ GEM reconstructions and curations that are released in the RAVEN Toolbox version 2.0.
- feat: add new tutorial script `tutorial2018.m`. This script provides extensive explanations and instructions through demonstrating the utilization of the newly developed RAVEN 2.0 features and functions on GEM reconstruction and refinement for _Streptomyces coelicolor_ strain A3(2).
- feat: add metadata files required for the new exercise

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [X] Selected `devel` as a target branch

### CODE REVIEW

**Comment by edkerk** [comment]
For consistency, it might be better to continue the numbering of tutorials and rename `tutorial2018.m` to `tutorial5.m`?

**Comment by Hao-Chalmers** [comment]
The script name `tutorial2018` is more informative than `tutorial5`. And the consistency is still reserved in 'RAVEN mini tutorial.docx' file by continually number the new tutorial as Exercise 5.

**Comment by edkerk** [comment]
But that is exactly what is not consistent. Numbering exercises 1-5 but not doing that with the `tutorial.m`-files.

**Comment by Hao-Chalmers** [comment]
My first thought actually was `tutorial5` for the name. But such simple-numbered system will be problematic in the long run, and thus more [semantic notations](https://github.com/orgs/SysBioChalmers/teams/everyone/discussions/1) should be used. As I explained, `tutorial2018` is more informative. There wouldn't be inconsistence/confusiton as long as this script name and the Exercise is explicitely associated.

**Comment by edkerk** [comment]
This is _not_ semantic notation, `tutorial2018` is _not_ more informative (what does it matter what year it was from?), and different numbering of exercises and script _is_ confusing (all other exercises and scripts match in number, except from 5 and 2018), but I'll accept this PR anyway.

**Pull request merged**
