### PR TITLE
fix: if FASTA file in dir containing spaces

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
- feat:
  - `checkFileExistence` can additionally copy files to the system default temporary directory and return the full path
- fix:
  - functions that use a species FASTA file as input (`getBlast`, `getDiamond`, `getKEGGModelForOrganism` and `getMetaCycModelForOrganism`) will copy this FASTA file to a temporary directory to avoid potential issues with the original path when running external software (e.g. BLAST)

To test, run `getBlast` on FASTA files located in a folder with spaces ('test directory'):
```matlab
pathStr = fileparts(which('Sco_all_protein.faa'));
cd(pathStr)
mkdir 'test directory'
copyfile '*.fa*' 'test directory/'
test=getBlast('test','test directory/Sco_all_protein.faa','test2','test directory/sce.fa');
rmdir('test directory')
```

**I hereby confirm that I have:**

- [x] Tested my code on my own machine
- [x] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [x] Selected `devel` as a target branch
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about this PR

### CODE REVIEW

**Comment by edkerk** [comment]
Would be nice to see if this works on Mac.

**Comment by simas232** [comment]
FYI, I no longer have a Mac. @Hao-Chalmers, could you please check this PR in your system?

**Comment by Hao-Chalmers** [comment]
will do

**Review by Hao-Chalmers — APPROVED** [review]
test code works well on Mac

**Pull request merged**
