### PR TITLE
feat: distribute libSBML

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
- feat:
  - distribute libSBML binaries to simplify RAVEN installation
  - force the use of RAVEN-provided libSBML binaries

This greatly simplifies installation of RAVEN, as users no longer have to separatedly download and install libSBML. To make sure that RAVEN uses the binaries provided with this repo, and not any other libSBML that might be installed elsewhere/provided by other toolboxes, `importModel` and `exportModel` explicitly navigate to the correct folder to direct MATLAB to the preferred binaries.

After merging, README.md and Wiki should be modified to reflect this change.

**I hereby confirm that I have:**

- [x] Tested my code on my own machine
- [x] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [x] Selected `devel` as a target branch
    Temporarily selected `feat/glpk`, until PR #408 is merged
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about this PR

### CODE REVIEW

**Review by feiranl — APPROVED** [review]
Works perfectly with MAC.

*** THE RAVEN TOOLBOX ***

 > Checking RAVEN release:              DEVELOPMENT
 > Checking MATLAB release:             2019b
 > Set RAVEN in MATLAB path:            Pass

=== Model import and export ===
 > Add Java paths for Excel format:     Pass
 > Check libSBML version:               5.19.0
 > Checking model import and export:
   > Import Excel format:               Fail
   > Export Excel format:               Fail
   > Import SBML format:                Pass
   > Export SBML format:                Pass

=== Model solvers ===
 > Checking for functional LP solvers:
   > glpk:                              Pass
   > gurobi:                            Fail
   > cobra:                             Fail
 > Checking for functional MILP solvers:
   > glpk:                              Pass
   > gurobi:                            Fail
   > cobra:                             Fail
 > Set RAVEN solver:                    glpk

=== Essential binary executables ===
 > Checking BLAST+:                     Pass
 > Checking DIAMOND:                    Pass
 > Checking HMMER:                      Pass

=== Compatibility ===
 > Checking function uniqueness:        Pass

*** checkInstallation complete ***

**Comment by edkerk** [comment]
@feiranl 

Could you please also check the following, to make sure it is using the intended libSBML binary:

```matlab
[ravenDir,prevDir]=findRAVENroot();
cd(fullfile(ravenDir,'software','libSBML'));
which TranslateSBML
cd(prevDir)
```

Does it report the `TranslateSBML.mex*` from the RAVEN repo?

**Comment by feiranl** [comment]
Yes, it does report.

`/GitHub/RAVEN/software/libSBML/TranslateSBML.mexmaci64
`

**Comment by mihai-sysbio** [comment]
Any thoughts on why the GH Actions [returns an error in the comment above](https://github.com/SysBioChalmers/RAVEN/pull/409#issuecomment-1098069239)?

> Error occurred in fillGapsLargeTests/testLargeGurobi and it did not run to

**Comment by edkerk** [comment]
Probably because gurobi solver is not installed. This is the output when running `runtests('fillGapsLargeTests')` locally, if I remove Gurobi from MATLAB path:

```
Running fillGapsLargeTests

================================================================================
Error occurred in fillGapsLargeTests/testLargeGurobi and it did not run to completion.
    ---------
    Error ID:
    ---------
    ''
    --------------
    Error Details:
    --------------
    Error using fillGapsLargeTests>testLargeGurobi (line 64)
    Solver not working
================================================================================
.
================================================================================
Error occurred in fillGapsLargeTests/testLargeCobra and it did not run to completion.
    ---------
    Error ID:
    ---------
    ''
    --------------
    Error Details:
    --------------
    Error using fillGapsLargeTests>testLargeCobra (line 98)
    Solver not working
================================================================================
.
Done fillGapsLargeTests
__________

Failure Summary:

     Name                                Failed  Incomplete  Reason(s)
    ===================================================================
     fillGapsLargeTests/testLargeGurobi    X         X       Errored.
    -------------------------------------------------------------------
     fillGapsLargeTests/testLargeCobra     X         X       Errored.

ans = 

  1×2 TestResult array with properties:

    Name
    Passed
    Failed
    Incomplete
    Duration
    Details

Totals:
   0 Passed, 2 Failed (rerun), 2 Incomplete.
   14.1713 seconds testing time.
```

From the github-actions bot comment it is not obvious whether the rests of the tests are run, is there a maximum length of the comment text?

**Comment by mihai-sysbio** [comment]
@edkerk thank you for the investigation. It was just the inadequate parsing of the test results. https://github.com/SysBioChalmers/RAVEN/pull/411 should address this. I'll look into why Gurobi is misbehaving.

**Review by simas232 — APPROVED** [review]
Everything works perfectly in Kubuntu 22.04 using MATLAB 2021a. I got almost the same output like @feiranl, just in my case Excel I/O tests passed.

**Review by haowang-bioinfo — APPROVED** [review]
Works well on latest Mac using MATLAB 2021a, got a Pass on every test.

**Comment by mihai-sysbio** [comment]
> Probably because gurobi solver is not installed. This is the output when running `runtests('fillGapsLargeTests')` locally, if I remove Gurobi from MATLAB path:

I'm not sure if that's really the case:

```
>> checkInstallation

*** THE RAVEN TOOLBOX v.2.6.2 ***

MATLAB R2020b detected

Checking if RAVEN is on the MATLAB path...									OK
Checking if it is possible to parse a model in Microsoft Excel format...	OK
Checking if it is possible to import an SBML model using libSBML...			The model contains 0 errors and 1 warnings.

OK
Solver found in preferences... gurobi
Checking if it is possible to solve an LP problem using gurobi...			OK
Checking if it is possible to solve an LP problem using cobra...			Not OK
Preferred solver... KEPT
Solver saved as preference... gurobi

Checking essential binary executables:
	BLAST+... OK
	DIAMOND... OK
	HMMER... OK
Checking whether RAVEN functions are non-redundant across MATLAB path...	OK

*** checkInstallation complete ***

>> runtests(struct2table(dir('*.m')).name);
Running blastPlusTests
.
Done blastPlusTests
__________

Running cdhitTests
.
Done cdhitTests
__________

Running diamondTests
.
Done diamondTests
__________

Running fillGapsLargeTests
.
================================================================================
Error occurred in fillGapsLargeTests/testLargeCobra and it did not run to completion.
    ---------
    Error ID:
    ---------
    ''
    --------------
    Error Details:
    --------------
    Error using fillGapsLargeTests>testLargeCobra (line 98)
    Solver not working
================================================================================
.
Done fillGapsLargeTests
__________

Running fillGapsSmallTests

================================================================================
Error occurred in fillGapsSmallTests/testSmallGlpk and it did not run to completion.
    ---------
    Error ID:
    ---------
    ''
    --------------
    Error Details:
    --------------
    Error using dispEM (line 49)
    Such solver is not compatible with RAVEN. Available options are 'gurobi' and 'cobra'
    
    
    Error in setRavenSolver (line 22)
        dispEM(EM);
    
    Error in fillGapsSmallTests>testSmallGlpk (line 16)
    setRavenSolver('glpk');
================================================================================
..
================================================================================
Error occurred in fillGapsSmallTests/testSmallCobra and it did not run to completion.
    ---------
    Error ID:
    ---------
    ''
    --------------
    Error Details:
    --------------
    Error using fillGapsSmallTests>testSmallCobra (line 98)
    Solver not working
================================================================================
.
Done fillGapsSmallTests
__________

Running hmmerTests
.
Done hmmerTests
__________

Running importExportTests
....
Done importExportTests
__________

Running mafftTests
.
Done mafftTests
__________

Running miriamTests
.
Done miriamTests
__________

Running solverTests

================================================================================
Error occurred in solverTests/testGlpk and it did not run to completion.
    ---------
    Error ID:
    ---------
    ''
    --------------
    Error Details:
    --------------
    Error using dispEM (line 49)
    Such solver is not compatible with RAVEN. Available options are 'gurobi' and 'cobra'
    
    
    Error in setRavenSolver (line 22)
        dispEM(EM);
    
    Error in solverTests>testGlpk (line 14)
    setRavenSolver('glpk');
================================================================================
...
Done solverTests
__________

Running sortIdentifiers_and_permuteModelTests
.
Done sortIdentifiers_and_permuteModelTests
__________

Running tinitTests
.
Done tinitTests
__________

Failure Summary:

     Name                               Failed  Incomplete  Reason(s)
    ==================================================================
     fillGapsLargeTests/testLargeCobra    X         X       Errored.
    ------------------------------------------------------------------
     fillGapsSmallTests/testSmallGlpk     X         X       Errored.
    ------------------------------------------------------------------
     fillGapsSmallTests/testSmallCobra    X         X       Errored.
    ------------------------------------------------------------------
     solverTests/testGlpk                 X         X       Errored.
```

My suggestion would be to merge this PR as is, and open up a new issue to investigate the failures.

**Comment by edkerk** [comment]
@mihai-sysbio That output seems to use two different RAVEN versions? The `fillGapsSmallTests` was introduced in PR #408, but also `checkInstallation` and `setRavenSolver` were updated. The output above seems to use older `checkInstallation` and `setRavenSolver` functions.

**Comment by mihai-sysbio** [comment]
@edkerk alright let's see how this behaves in future PRs, now that Gurobi is working fine.

**Pull request merged**
