### PR TITLE
fix: use rev field in constructEquation, metaData in writeYaml, model.description to model.name and correct parse taxonomy URL

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
- fix:
  - `constructEquation` is used by `exportToExcelFormat` and `exportForGit` to write model file. In SBML,LB, UB and reaction reversibility are included as: `<reaction metaid="r_3135" [...] reversible="false" [...] fbc:lowerFluxBound="FB3N0" fbc:upperFluxBound="FB5N1000">`. So reversibility is a separate characteristic, not necessarily defined by the bounds. Therefore, when writing Excel and text file it should also use the rev field, and not the LB and UB, to define reaction reversibility. Old functionality is retained when particular use cases require it
  - `importModel` parse taxonomy URL if `https:\\` is defined
  - `importModel` handle metabolite names with both `[*]` in the name and a `[compartment]` suffix
  - `importModel` prevent duplicating SBO terms
- feature:
  - new model fields `model.annotation.authors`, `model.annotation.sourceUrl`, `model.version` and `model.date` (solves #311)
  - `writeYaml` writes meta data in `yml` file (solves #311)
- refactor:
  - rename `model.description` to `model.name` (solves #311)

**I hereby confirm that I have:**

- [x] Tested my code on my own machine
- [x] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [x] Selected `devel` as a target branch

### CODE REVIEW

**Review by simas232 — APPROVED** [review]
Great implementations, @edkerk! I also updated KEGG and MetaCyc binaries to reflect these changes and fixed several typos.

**Review by Hao-Chalmers — APPROVED** [review]

**Comment by simas232** [comment]
Oh, I think we forgot the fix tutorials, do not merge this PR yet.

**Comment by simas232** [comment]
I implemented the fixes in the tutorial files, please have a check and proceed with the PR merge.

**Comment by edkerk** [comment]
An issue with incorrect indentation of [`yeastGEM.yml`](indentation) was identified, fixing `writeYaml` atm.

**Comment by edkerk** [comment]
`writeYaml` now generates valid `yml` files as shown by https://github.com/SysBioChalmers/yeast-GEM/pull/256 passing CI.

**Pull request merged**
