### PR TITLE
fix: remove Mosek, refactor LP and MILP parsing, optimizeProb bug

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
Addressing issue #245, LP and MILP problem structures and results are now formatted in COBRA style (was MOSEK style).

PR #256 (author: @JonathanRob) is merged with this PR.

_Simple_ LP has been tested (`solveLP` with a classic GEM), and `fillGaps` also seems to work fine, but additional test runs are encouraged.

**I hereby confirm that I have:**

- [x] Tested my code on my own machine
- [x] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [x] Selected `devel` as a target branch
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about this PR

### CODE REVIEW

**Comment by edkerk** [comment]
@JonathanRob Can you specifically confirm that this also fixes #256? Thanks!

**Comment by JonathanRob** [comment]
Hmm, it looks like `runINIT` now encounters an error. The `runINIT` function sets up the `prob` structure but it doesn't have a `b` field, so line 4 in `cobraToGurobiProb` (`gprob.rhs = prob.b;`) errors with missing field `b`. Instead, `prob` from `runINIT` has `bux`, `blx`, `buc`, and `blc` - I'm not super familiar with the different solver parameters, so I'm not sure how this should be translated. Here is the full error message if that helps:

```
Error in cobraToGurobiProb (line 4)
gprob.rhs = prob.b;

Error in optimizeProb (line 30)
res = gurobi(cobraToGurobiProb(prob),gparams);

Error in runINIT (line 308)
res=optimizeProb(prob,params);
```

**Comment by edkerk** [comment]
Thanks @JonathanRob. The `bux`, `blx`, `buc` and `blc` where used in the previous MOSEK-style `prob`. I'll fix this and check with you again.

**Comment by edkerk** [comment]
@simas232 @JonathanRob @Hao-Chalmers could you please check whether this works for `runINIT`?

**Comment by edkerk** [comment]
I noticed that in the release notes for 2.3.0 is mentioned that PR #256 was solved, but that PR was actually closed as it's changes are also included here. So this PR should be reviewed and merged with `devel` to solve PR #256, in addition to the issues mentioned in this PR (removal of MOSEK, refactoring of LP and MILP problems).

**Comment by JonathanRob** [comment]
I was able to repair tINIT functionality with the new problem structure, as well as improve some features.

The main problem was that the specification of which variables were integers in the MILP setup was not formatted correctly in the new `prob` structure. This was resolved by adding variable types to the `prob.vartype` field (d8795a8), which also required updating the `cobraToGurobiProb` (e16a2cd) and `optimizeProb` (bfd5199) functions to recognize/use this new field.

An additional error was caused by the `gurobiToCobraRes` function, which would consider the optimization failed if the `vbasis` and `cbasis` fields were missing from the solution structure. Since these fields are not available for MILPs, the function has been modified to skip this part if the problem was a MILP (5c1a0fd). The `optimizeProb` function now also informs the `gurobiToCobraRes` function whether the problem is a MILP (60e15dc).

Finally, I modified the `gurobiToCobraRes` function to consider a MILP as optimized/successful if the time limit is reached, as long as it has found a solution(s) within the time limit (6fd85c1). This is necessary for tINIT, which for large models will virtually always exceed the time limit.

After implementing these changes, I ran a test with tINIT using identical data as a previous run I had done with the old version. The run behaved similarly, and yielded models that were very close in structure (as close as one can expect with the inherent stochasticity of the algorithm) to the previous results. I think it is safe to say that tINIT is now fully functional with these new updates, but I will continue to check closely for any other bugs that I may have missed.

**Comment by edkerk** [comment]
Thank you @JonathanRob for the testing and fixing. It should really be just an issue of refactoring the problem structure, so if identical results are obtained then the refactoring was succesful. I also confirmed that your changes does not break ´fillGaps´, which I've used as test case for MILP problems.

**Pull request merged**
