### PR TITLE
Refactor/raven cobra wrapper

### PR DESCRIPTION
**Pull request by BenjaSanchez**
### Main improvements in this PR:

As suggested by @Hao-Chalmers, I refactored `ravenCobraWrapper` to read a `.csv` file with namespace/COBRA field pairs. Note that `metKEGGID`, `metPubChemID` and `rxnReferences` were left out as they have specific ways in which they are treated. Other things this PR includes:
* All bugs mentioned in #285 are solved with the refactoring.
* On the COBRA side, `REACTOME` is changed to `Reactome` (for both rxn/mets)
* On the RAVEN side:
  - `reactome.metabolite` is changed to `reactome`
  - `metacyc` is changed to `biocyc` (for both rxn/mets) after @edkerk's recommendation
* updated docstring

Pending ids that COBRA does not recognize yet:

* `geneSGDID`
* `geneSBOTerms`
* `metEnviPathID`
* `metLIPIDMAPSID`
* `metSABIORKID`
* `metSLMID`
* `rxnSABIORKID`

To allow those, a new PR to COBRA similar to https://github.com/opencobra/cobratoolbox/pull/1591 is needed.

### Code test

Tested in [this commit](https://github.com/SysBioChalmers/yeast-GEM/commit/de4e4ee686795b6341a14df40a8e7b5497032a63) of a test branch in the yeast model, where nothing changes compared to the previous commit (using RAVEN in `devel`).

**I hereby confirm that I have:**

- [x] Tested my code on my own machine
- [x] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [x] Selected `devel` as a target branch

### CODE REVIEW

**Comment by Hao-Chalmers** [comment]
Beautiful!

**Comment by edkerk** [comment]
Something went wrong.

- I refactored some code, so that it would use the COBRA_stucture_fields.csv from [cobratoolbox](https://github.com/opencobra/cobratoolbox/blob/develop/src/base/io/definitions/COBRA_structure_fields.csv), to simplify future integration into COBRA, with commit https://github.com/SysBioChalmers/RAVEN/commit/9d4ffe74ef3b18cdd0115b0eaedc4519f31f8c32
- I refactored `ravenCobraWrapper` to remove duplicate code for fields that are identical between the two model types, commit https://github.com/SysBioChalmers/RAVEN/commit/2d8b5a452f324315b422ba9b6a346c730a5931f7
- I wrote a new function that corrects the order of the model fields for both RAVEN and COBRA models: https://github.com/SysBioChalmers/RAVEN/commit/bae8effc2bd0c74edcc254e98b9c7e0d58608d72

Normally I could just push to branch on GitHub and it would appear in the PR, but because this was a PR from @BenjaSanchez own fork, this did not work. Commit https://github.com/SysBioChalmers/RAVEN/commit/a1e4c9dd5bf4f182e06f1efe4254c6e158f8eabe now seems to contain a lot of changes. However, it seems like the branch was merged with a slightly earlier state of the `devel` branch, which means that this commit now also includes the changes of removing MOSEK (from PR #258). I don't understand this fully, but comparing that PR and the recent commit, it seems that any _unexpected_ changes in that commit are identical to those pushed by that PR.

**Comment by edkerk** [comment]
So I did not mean to merge with review, but will have to figure out how to do this better next time... Anybody experience with this, pushing changes to a PR from a forked repo?

**Comment by BenjaSanchez** [comment]
@edkerk nice! you forgot to consider the edge cases `metKEGGID` and `metPubChemID`: As you can see in [this test commit](https://github.com/SysBioChalmers/yeast-GEM/commit/4f67426b1f333439f5bb94cdcae6c4376b058e32), now the wrapping does not work as intended, as the met KEGG ids are converted twice. This can be solved by adapting L44 in `ravenCobraWrapper` to:

```matlab
dbFields        = dbFields & ~contains(fieldFile{1},{'metInChIString','metKEGGID','metPubChemID','rxnECNumbers','rxnReferences'});
```

I tested it in [this commit](https://github.com/SysBioChalmers/yeast-GEM/commit/ad28e44a002d6f97da8ee1019233aea6d4ad3645) and it works as intended. I would open a PR myself but I'm scared to create chaos again 😅 

wrt the merge, I have never experienced what you mention: pushing to someone else's branch should be doable as long as the creator of the PR ticks the box "allow edits from maintainers" (which I did) and should not "auto-merge" anything. But to decrease additional problems in the future, I'd be happy to be added as a collaborator to the repo 🙃

**Pull request merged**
