### PR TITLE
fix: disable adding prefix 'M_' and 'R_' in exprotModel function

### PR DESCRIPTION
**Pull request by Hao-Chalmers**
### Main improvements in this PR:
* This PR modify `exportModel` function to stop adding by prefix `M_` and `R_` to metabolite and reactions ids, as proposed in #353

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [X] Selected `devel` as a target branch
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about this PR

### CODE REVIEW

**Comment by edkerk** [comment]
To my opinion, `importModel` should then also be changed, see my comment in #353.

**Comment by edkerk** [comment]
Also, I suggest this would be part of a minor release (2.5.2 -> 2.6.0). It will break compatibility.

**Review by mihai-sysbio — CHANGES_REQUESTED** [review]
Very nice to have this fix in Raven. I noted a few things
- [x] in `io/exportModel.m:510` this should be updated `rdf:about="#meta_R_' model.rxns{i} '"`
- [ ] there's a reference to `meta_M` in `doc/io/exportModel.html:391` and to `meta_R` in the same file on line `569`
- [x] ~I think @edkerk noted that there is no function that reports all SBML-invalid identifiers, which I agree should be part of this PR that solves #353~ see below

**Comment by mihai-sysbio** [comment]
>     * [ ]  I think @edkerk noted that there is no function that reports all SBML-invalid identifiers, which I agree should be part of this PR that solves [refactor: remove prefix 'M_' and 'R_' in exprotModel/importModel functions #353](https://github.com/SysBioChalmers/RAVEN/issues/353)

On second thought, @edkerk would it be okay to resolve the concern above as a different PR, to keep PRs small and targeted? This PR will then resolve only a part of #353, which makes sense to me.

**Review by edkerk — CHANGES_REQUESTED** [review]
- [x] Remove line 225-231, where `c_` is appended to `model.comps`.

**Comment by Hao-Chalmers** [comment]
>  there's a reference to meta_M in doc/io/exportModel.html:391 and to meta_R in the same file on line 569

the html files will be corrected by the `m2html` later

**Comment by edkerk** [comment]
We have the routine to run `updateDocumentation` just before making a new release (example #357), but it doesn't hurt to run it earlier already.

**Review by edkerk — APPROVED** [review]
Successful I/O of `yeast-GEM`.

**Review by mihai-sysbio — APPROVED** [review]

**Comment by Hao-Chalmers** [comment]
Here I merge this since `tiny progress is still progress`.  The ID check function and `importModel` will be modified in other PRs.

**Pull request merged**
