### PR TITLE
chore: rename master to main

### LINKED ISSUE #382: rename `master` to `main`
### Description of the issue:
The `master` branch should be renamed to `main`.
In addition:
- [ ] the wiki repository should also update any reference from `master` to `main`
- [ ] the documentation should be regenerated

**I hereby confirm that I have:**
- [x] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [x] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

*Note: replace [ ] with [X] to check the box. PLEASE DELETE THIS LINE*

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:
This PR fixes #382 .

**I hereby confirm that I have:**

- [ ] Tested my code on my own machine
- [x] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [x] Selected `devel` as a target branch
- [x] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about this PR

In accordance to the original issue, this PR should also resolve:
- [x] the wiki repository should also update any reference from `master` to `main`
- [x] the documentation should be regenerated
- [ ] rename the branches on GitHub

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
Just to confirm, is the intention to keep supporting the branch flag?

**Comment by edkerk** [comment]
> Just to confirm, is the intention to keep supporting the branch flag?

You mean in relation to your changes in d8e74f89a9f5e067b02969e26b48882ed0475303? Actually, for me it's fine either way, not essential for the toolboxes to be in `main`. What matters in each push/PR to git (what these functions are for) is the changes made to the model, and that one should review anyway. But I can also see the argument that one might only want to use 'stabile' toolboxes to write model files for the `main` branch, even though 'stabile' is quite subjective...

**Comment by edkerk** [comment]
Sorry, clicked on "ready to review" by mistake, don't know how to make it a draft again.

**Comment by mihai-sysbio** [comment]
Thanks for the response @edkerk. Then I guess we can continue to keep the code as-is, with the change that `main` is also considered the stable branch in addition to `master`.
Are there any instructions on how to generate updated documentation? Or maybe this doesn't need to be part of the current PR?

**Comment by edkerk** [comment]
> [...] with the change that `main` is also considered the stable branch **in addition to** `master`.

But `main` _replaces_ `master`, so I'm not sure what you mean with _in addition to_? Note that `masterFlag` in `exportForGit` is logical, not string, so the name of the stabile branch doesn't matter.

> Are there any instructions on how to generate updated documentation? Or maybe this doesn't need to be part of the current PR?
There are no instructions, but it would probably be good to have this all included in one PR?

**Comment by mihai-sysbio** [comment]
> But `main` _replaces_ `master`, so I'm not sure what you mean with _in addition to_?

cobratoolbox is still using `master`, thus both branch names are accepted.

> Note that `masterFlag` in `exportForGit` is logical, not string, so the name of the stabile branch doesn't matter.

Indeed, I just thought that `masterFlag` was a bit vague, and that `mainFlag` was worse, so I took the opportunity to rename the parameter to `mainBranchFlag`.

**Comment by mihai-sysbio** [comment]
I'm more on a "if it ain't broke don't fix it" with this one, so I'm not really tempted to change the behavior of the `mainBranchFlag`. Plus, I feel it's beyond the scope of this branch renaming to take care of that.

It seems I can't generate the documentation without triggering a lot of changes, eg dates in all files, and also changes in path separator (from Windows to Linux style), so I will mark this as `ready for review`, leaving the documentation generation to the release PR or to someone who can generate it reliably.
For reference, this was the command that I used
```
m2html('mfiles', '.', 'htmldir', 'doc', 'recursive', 'on')
```

**Comment by edkerk** [comment]
Have you tried running `updateDocumentation`?

**Comment by mihai-sysbio** [comment]
Ah that's what I was after when asking if there are any instructions on how to generate updated. documentation.

`updateDocumentation` still presented problems with `\` vs `/`. It was easier this time though to check the changes, since it was for 30+ files instead of 200+./

**Review by edkerk — APPROVED** [review]
I also changed the mentions in the Wiki, only thing left is the actual renaming in GitHub?

**Comment by mihai-sysbio** [comment]
I think so! The nicest way seems to be to go to https://github.com/SysBioChalmers/RAVEN/branches and click the small 🖊️  edit button on the right side of the page for branch `master`. This will also notify other users of the repository.

**Pull request merged**
