### PR TITLE
Fix/id compliance cobra wrapper

### PR DESCRIPTION
**Pull request by BenjaSanchez**
### Main improvements in this PR:

I updated `ravenCobraWrapper.m` to store annotation in a way that is compliant with [identifiers.org](https://registry.identifiers.org/registry) & cobratoolbox:

* 1 namespace was deleted and 2 namespaces were renamed
* For any annotation field not included in [this list](https://github.com/opencobra/cobratoolbox/blob/master/src/base/io/definitions/COBRA_structure_fields.csv), the convention of a `rxn/met`+`is` prefix to the namespace, together with an `ID` suffix, should be used. In addition, the name should be SBML compatible (i.e. the character `.` should be stored as `__46__`).

These changes are needed for adding BiGG ids to the yeast model (see https://github.com/SysBioChalmers/yeast-GEM/pull/188). Below all the COBRA fields corrected, showing the old & compliant name based on the namespace:

|old name      |namespace in identifiers.org|compliant name          |
|--------------|----------------------------|----------------------------|
|rxnBiGGID     |bigg.reaction               |rxnisbigg__46__reactionID   |
|rxnMetaCycID  |metacyc.reaction            |rxnismetacyc__46__reactionID|
|rxnREACTOMEID |reactome                    |rxnisreactomeID             |
|rxnRheaID     |rhea                        |rxnisrheaID                 |
|rxnSABIORKID  |sabiork.reaction            |rxnissabiork__46__reactionID|
|rxnSEEDID     |seed.reaction               |rxnisseed__46__reactionID   |
|metBiGGID     |bigg.metabolite             |metisbigg__46__metaboliteID |
|metEnviPathID |envipath                    |metisenvipathID             |
|metLIPIDMAPSID|lipidmaps                   |metislipidmapsID            |
|metMetaCycID  |metacyc.compound            |metismetacyc__46__compoundID|
|metREACTOMEID |**does not exist**                           |**deleted**                           |
|metSABIORKID  |sabiork.compound            |metissabiork__46__compoundID|
|metSEEDID     |seed.compound               |metisseed__46__compoundID   |
|metSLMID      |slm                         |metisslmID                  |

**I hereby confirm that I have:**

- [x] Tested my code on my own machine
- [x] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [x] Selected `devel` as a target branch

### CODE REVIEW

**Comment by Hao-Chalmers** [comment]
@BenjaSanchez very good initiative in standardising `ravenCobraWrapper` with "identifiers.org" and COBRA.

In this PR, the proposed commits are based on above curated table. How about directly add this namespace table as `tsv` to RAVEN, because it could be used for other purposes as well: e.g. model structure verification, identifier id mapping.

In addition, this table mostly likely needs to be reguarly updated for adding/removing elements. It is therefore better to adjust `ravenCobraWrapper` so that it depends on this table but without having those annotation fields hardcoded.

**Comment by edkerk** [comment]
Note that the compliant field names are due to COBRA Toolbox not fully parsing these annotation fields when reading the model file. There is currently a PR open (https://github.com/opencobra/cobratoolbox/pull/1591) that adds support for some of these fields (e.g. `rxnBiGGID`, `rxnSEEDID`), but this can also be expanded to include **all** the fields suggested here. It would be better to fix this directly at COBRA Toolbox then to modify RAVEN to mimic the COBRA behaviour. Not sure what the ETA is on the PR at COBRA.

**Comment by edkerk** [comment]
Notwithstanding, `metREACTOMEID` and `rxnREACTOMEID` should be `metReactomeID` and `rxnReactomeID` to be compatible with (https://github.com/opencobra/cobratoolbox/pull/1591).

**Comment by BenjaSanchez** [comment]
@edkerk agreed that the best would be that COBRA adapts their behavior (as the compliant names are quite ugly), but as it doesn't seem that any development is being done over there, I decided to create a PR here. Feel free to keep this one open until they get back to you, and if they are willing to change, you can close this one. Note that there are a couple things in this PR that should be included in the wrapper regardless:
* On the RAVEN side the `sabiork.metabolite`/ `swisslipid` namespaces should change to `sabiork.compound`/`slm`, respectively
* The keyword `BiGGID` is misspelled in some sections as `BIGGID`.
* There are 2 inconsistencies of field names (L540 and L615 of the original file, see below)
  image

In the meantime I will be using this RAVEN branch to update the yeast model, to allow saving BiGG ids in the `.yml` file.

@Hao-Chalmers the idea of having a conversion between namespaces and COBRA ids is a good one and would make the wrapper much less verbose. Once there's agreement from both sides on the naming standards I'd be happy to implement it.

**Comment by edkerk** [comment]
PR opencobra/cobratoolbox#1591 is now merged with their `develop`, but this did not solve all issues reported here:

|old name      |namespace in identifiers.org|compliant name          |
|--------------|----------------------------|----------------------------|
|~~rxnBiGGID~~     |~~bigg.reaction~~               |~~rxnisbigg__46__reactionID~~   |
|**rxnMetaCycID**  |**metacyc.reaction**            |**rxnismetacyc__46__reactionID**|
|~~rxnREACTOMEID~~ |~~reactome~~                    |~~rxnisreactomeID~~             |
|~~rxnRheaID~~     |~~rhea~~                        |~~rxnisrheaID~~                 |
|**rxnSABIORKID**  |**sabiork.reaction**            |**rxnissabiork__46__reactionID**|
|~~rxnSEEDID~~     |~~seed.reaction~~               |~~rxnisseed__46__reactionID~~   |
|~~metBiGGID~~     |~~bigg.metabolite~~             |~~metisbigg__46__metaboliteID~~ |
|**metEnviPathID** |**envipath**                    |**metisenvipathID**             |
|**metLIPIDMAPSID**|**lipidmaps**                   |**metislipidmapsID**            |
|**metMetaCycID**  |**metacyc.compound**            |**metismetacyc__46__compoundID**|
|~~metREACTOMEID~~ |~~**does not exist**~~                           |~~**deleted**~~                           |
|**metSABIORKID**  |**sabiork.compound**            |**metissabiork__46__compoundID**|
|~~metSEEDID~~     |~~seed.compound~~               |~~metisseed__46__compoundID~~   |
|**metSLMID**      |**slm**                         |**metisslmID**                  |

- For the other fields, I suggest a new PR is made at [opencobra/cobratoolbox](https://github.com/opencobra/cobratoolbox/). Regarding `metEnviPath`, `met/rxnSABIORKID`, I'm not sure these are widely used and they are redundant to the other databases, so not necessarily worth the effort. `metSLMID` and `metLIPIDMAPS` would be good to implement in COBRA Toolbox, as lipids are typicaly not well covered by other databases.

- Regarding `met/rxnMetaCycID`, one can use the more general `met/rxnBioCycID`, which were included in opencobra/cobratoolbox#1591. A MetaCyc ID is transformed in a BioCyc ID by appending the prefix `meta:`, e.g. `META:GLUCOKIN-RXN` instead of `GLUCOKIN-RXN`. Alternatively you could use the `YEAST:` prefix (i.e. `YEAST:GLUCOKIN-RXN`), specifically referring to _S. cerevisiae_. But a prefix **must** be specified, compare [with](https://biocyc.org/getid?id=YEAST:GLUCOKIN-RXN) and [without](https://biocyc.org/getid?id=GLUCOKIN-RXN). These changes should be applied on the model directly (append the appropriate prefix and rename field to `met/rxnBioCycID`).

The other issues raised by @BenjaSanchez still need to be solved: either revert the now implemented fieldnames here, or make a separate PR that only solves those issues.

**Comment by BenjaSanchez** [comment]
great! I will create a separate PR, as I would have to revert both commits here anyways to comply with the new standards. Will also add @Hao-Chalmers suggestion of including a separate file with all field/namespaces pairs (akin to the [COBRA file](https://github.com/opencobra/cobratoolbox/blob/master/src/base/io/definitions/COBRA_structure_fields.csv) but just 2 columns and including the missing fields from above).

@edkerk I was testing cobratoolbox in their `develop` branch now with your additions and could not succesfully save in the `.xml` file a BiGG id as annotation, below my code:

```matlab
model.metBiGGID = cell(size(model.mets));
model.metBiGGID{1}='h2o';
writeCbModel(model,'test_model.xml');
```

Are you able to successfully save any of the new annotation fields?

**Comment by edkerk** [comment]
@BenjaSanchez it's working here as it should, both with your code and a full I/O round with an [SBML file](https://github.com/SysBioChalmers/Sco-GEM/blob/master/ModelFiles/xml/Sco-GEM.xml) that has e.g. BIGG annotation (in that last case it doesn't give exactly the same file: the original is from cobrapy).

Setup: Windows 10; MATLAB 2019b; cobratoolbox `develop`

**Comment by BenjaSanchez** [comment]
@edkerk now it's working, must have been something with my fork. Thanks!

**Pull request closed without merging**
