### PR TITLE
feat: distribute glpk as free solver alternative

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
- feat:
  - distribute `glpk` as solver, including binaries
  - tests for LP solver, MILP solver (using `fillGaps`) and model I/O
- refactor:
  - `checkInstallation` uses unit_tests whenever possible, including MILP
  - simplified parsing of LP via `solveLP` and `optimizeProb`, without conversion functions

**I hereby confirm that I have:**
- [x] Tested my code on my own machine
- [x] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [x] Selected `devel` as a target branch
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about this PR

### CODE REVIEW

**Review by feiranl — APPROVED** [review]
Works perfectly on MAC.

**Comment by edkerk** [comment]
Would be nice to have this reviewed by a few people, to make sure the glpk binaries work for all.

**Comment by mihai-sysbio** [comment]
Another pass for macOS 💪🏻

**Comment by edkerk** [comment]
> It was surprising to see the license file is called `COPYING`, and also that the README under `GLPKmex` was removed.

- `COPYING` is what the file is called with the [GLPK code](https://www.gnu.org/software/glpk/)
- `README` removal was not meant to be, will put back :)

**Review by mihai-sysbio — APPROVED** [review]
👍🏻

**Pull request merged**
