### PR TITLE
fix/refactor: handling of grRules in getModelFromHomology and contractModel (+ small feats)

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
- fix:
  - `contractModel` keep complexes (AND relationship) together, resulting in some redundancy but correct grRules
  - `getModelFromHomology` correct brackets if multiple orthologs are included
- feat:
  - `expandModel` can give list of reactions to check
  - `setParam` can take 1 reaction ID as char, and if multiple reactions can changed it can take different paramTypes (e.g. {'lb','ub','ub','lb'})
  - `addGenesRaven` throw detailed warning instead of error if gene already exist
- doc:
  - `README.md` link to 'master' Zenodo URL, not version-specific

**I hereby confirm that I have:**

- [x] Tested my code on my own machine
- [x] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [x] Selected `devel` as a target branch

### CODE REVIEW

**Comment by edkerk** [comment]
Example of the `getModelFromHomology` and `contractModel` changes. For this, I first expand a template model (to split isoenzymes), then get homology model, followed by combining grRules of identical reactions (=contracting).

```matlab
>> modelTemp.grRules{41} % Selected reaction

ans =

    '(SCO5281 and SCO2181 and SCO0884) or (SCO5281 and SCO2181 and SCO2180) or (SCO5281 and SCO2181 and SCO4919) or (SCO5281 and SCO7123 and SCO0884) or (SCO5281 and SCO7123 and SCO2180) or (SCO5281 and SCO7123 and SCO4919) or (SCO5281 and SCO1268 and SCO0884) or (SCO5281 and SCO1268 and SCO2180) or (SCO5281 and SCO1268 and SCO4919)'

>> modelTempExp = expand(modelTemp); % Expand template model
>> modelNew = getModelFromHomology(modelTempExp,blastStruct,orgID);
>> modelNewContr = contractModel(modelSalb);
```
Note that SCO_2180 has two alternative orthologs, XNR_0677 and XNR_4702.

Previous outcome (XNR_4702 is added as non-complex isoenzyme at the end of grRule):
```matlab
modelNewContr.grRules{14} % Corresponding reaction in new model

ans =

    '(XNR_1523 and XNR_4701 and XNR_0677) or (XNR_1523 and XNR_4701 and XNR_4014) or (XNR_1523 and XNR_4701 and XNR_5676) or XNR_4702'
```

New outcome (XNR_4702 properly included as alternative to XNR_0677):
```matlab
modelNewContr.grRules{14} % Corresponding reaction in new model

ans =

    '(XNR_1523 and XNR_4701 and (XNR_0677 or XNR_4702)) or (XNR_1523 and XNR_4701 and XNR_4014) or (XNR_1523 and XNR_4701 and XNR_5676)'
```

**Comment by Hao-Chalmers** [comment]
@edkerk would be nice to have a testing toy model for evaluating such fix/refactor changes for dealing with complex `grRules`. What do you think?

**Comment by edkerk** [comment]
@Hao-Chalmers Would definitely be nice, but I will not implement this yet with our other discussion in mind.

**Review by Hao-Chalmers — APPROVED** [review]

**Comment by Hao-Chalmers** [comment]
everything looks good

**Pull request merged**
