### PR TITLE
feat: update GH Action workflow

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:

This PR aimed to update the GH Action dependencies and formatting. While doing so, a bug was spotted that highlighted that the latest RAVEN was actually not used, since the GH Action was relying on the system-provided RAVEN.

This PR also adds a corresponding badge in the Readme.

**I hereby confirm that I have:**

- [ ] Tested my code on my own machine
- [ ] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [x] Selected `devel` as a target branch
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about this PR

### CODE REVIEW

**Comment by edkerk** [comment]
Actually, maybe it is okay to leave out line 318 in `checkInstallation` completely? Missings files are also caught by status~=0 in line 319.

**Comment by mihai-sysbio** [comment]
It seems there is progress. The reported missing files are:
```
-           fullfile(binDir,'GLPKmex','glpkcc');
-           fullfile(binDir,'libSBML','TranslateSBML');
-           fullfile(binDir,'libSBML','OutputSBML');
```
And this is accurate, since these file names are missing their extensions.

**Comment by mihai-sysbio** [comment]
This PR is ready for review. Notes: soplex is installed, but not available due to dependencies, so all soplex tests will continue to fail for some time; the code now marks as executable also `.exe` dependencies.

**Comment by mihai-sysbio** [comment]
@edkerk if you'd prefer a slightly better solution, this could be a nice syntax to leverage:
```
chmod +x glpkcc.(mexa64|mexglx|mexmaci64)
```

While it doesn't _guarantee_ the existence of the right file for the platform, it avoids e.g. marking as executable the files for the Windows platform.

**Review by edkerk — APPROVED** [review]
Looks good!

**Comment by mihai-sysbio** [comment]
Looking again at the diff now - it looks weird and it should _not_ be merged yet.

**Review by edkerk — APPROVED** [review]

**Pull request merged**
